FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev pkg-config build-essential python3

COPY . /repo
WORKDIR /repo/mpy-cross
RUN make -j8
WORKDIR /repo/ports/unix
RUN make -j8

FROM ubuntu:22.04 as package
COPY --from=builder /repo/ports/unix/pycopy /
