FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev pkg-config build-essential

COPY . /repo
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3
WORKDIR /repo/mpy-cross
RUN make -j8
WORKDIR /repo/ports/unix
RUN make -j8
